# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "nick.psaris.com"
name: "nick.psaris.com"
url: "http://nick.psaris.com"
logo: "/assets/images/vecsig.png"
email: "nick@psaris.com"
description: >- # this means to ignore newlines until next line without indents
  Nick Psaris is a seasoned quantitative developer with experience
  building automated option market making and equity statarb backtesting
  and trading systems.
twitter_username: nickpsaris
github_username: psaris
minimal_mistakes_skin: air
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: America/New_York # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
    - "*.org"
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

analytics:
  provider: "google-gtag"
  google:
    tracking_id : "G-CLHDHWYNQ1"

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Nick Psaris"
  avatar : "/assets/images/nick.jpg"
  bio    : "ML, Q, MacBook and Emacs fan"
  links:
    # - label: "Website"
    #   icon: "fas fa-fw fa-link"
    #   url: "https://nick.psaris.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/nickpsaris"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/nickpsaris/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/psaris"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/nickpsaris/"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://www.facebook.com/nick.psaris/"
    - label: "Amazon"
      icon: "fab fa-fw fa-amazon"
      url: "https://www.amazon.com/Nick-Psaris/e/B00W7R5QD0"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/nickpsaris"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/nickpsaris/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/psaris"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/nickpsaris/"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://www.facebook.com/nick.psaris/"
    - label: "Amazon"
      icon: "fab fa-fw fa-amazon"
      url: "https://www.amazon.com/Nick-Psaris/e/B00W7R5QD0"

defaults:
  # all
  - scope:
      path: ""
    values:
      layout: single
      mathjax: true
      author_profile: true
      class: wide
      title: " "
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      toc: true
      toc_sticky: true
      layout: single
      read_time: false
      comments: true
      share: true
      related: true
      show_date: true
      future: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
year_archive:
  type: liquid
  path: /posts/
